services:
  flask_test:
    container_name: flask_test_required
    build: ./
    ports:
      - 8090:5000
    tty: true
    volumes:
      - ./:/workspace
    working_dir: /workspace
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
    # command: flask run --host=0.0.0.0
